### ISSUE TITLE
ERROR: There are no scenarios; must have at least one.

### ISSUE THREAD

**Issue by antonkratz** [bartwesselink/dbl-visualization#290]
I would like to run the app locally (the host is down... I realize that this repo is several years old but I am asking anyway, maybe I can still get it to run).

I am on Ubuntu 23.10.

I run into this:

> (base) kratz@akratz:~/work/dbl-visualization$ yarn
> 00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

**Comment by Masboes** [comment]
Hi, I think the yarn you're using there is not the package manager yarn, but Ubuntu's scenario manager also called yarn. See this https://stackoverflow.com/questions/53471063/yarn-error-there-are-no-scenarios-must-have-at-least-one

**Comment by RoanH** [comment]
Although running it yourself is probably the safest choice for extended use, I am also still hosting a version of the application at https://ngltree.roanh.dev/ if you need it.
